Fixing the assignation and de-assignation of reviewers of a PR
pozil/auto-assign-issue pull request #51
Opened 2022-06-14 16:04 UTC by agomezmoron

**Motivation: ** Assignation with PRs doesn't work. The same problem when removing assignees (for PRs also assignees = requested reviewers).

This fixes both issues and, depending on if it's a pull_request or issue, it use one or another flow.

2022-06-15 11:52 UTC, agomezmoron commented
Contribution done. The test fails internally when calling the octokit.rest.pulls.removeRequestedReviewers method but, according to [how the endpoint it works](https://octokit.github.io/rest.js/v18), the source code of the plugin-rest-endpoint-methods library and its [documentation](https://github.com/octokit/plugin-rest-endpoint-methods.js/blob/61bbc9ae4df28bf5c389f6536855c5ed2dbfe8b3/docs/pulls/removeRequestedReviewers.md), the "reviewers" attribute is needed:

Output of jest:

```
- Expected
    + Received

      Object {
        "owner": "mockOrg",
        "pull_number": 667,
        "repo": "mockRepo",
    +   "reviewers": Array [
    +     "userA",
    +     "userB",
    +   ],
      },
```

I left the test failing because I'm not a jest expert but, honestly, I'm not sure why it fails.

2022-06-15 11:55 UTC, pozil commented
@agomezmoron thanks for the contrib.
CI complains that `package.json` and `package-lock.json` are not in sync. Can you fix this?

2022-06-15 11:59 UTC, agomezmoron commented
Fixed @pozil . I would appreciate a check on your side too to see if I was missing something with Jest (I'm not an expert using it and I did my best).

2022-06-15 12:04 UTC, pozil commented
Sure, I'm quite busy today and tomorrow but I'll check it out on Friday.
Some of the new tests are failing and more problematic: it looks like there's a regression on the `works with project card events` test (it was passing before and the feature was functional).

2022-06-16 04:59 UTC, agomezmoron commented
The regression has been fixed (in the card, the issue number comes always as an issue independent on the case if it's a real issue or PR). So I had to write a method to check if it's an issue (trying to get it) and, if an exception is raised internally, leave it as non issue (so it's a PR). I'm not very happy with that implementation but after checking all the REST API, it's the only way: trying to retrieve an issue (or a PR) by an ID and, if it's not exist, so is the opposite thing.

2022-06-16 08:28 UTC, agomezmoron commented
I worked on the tests and now all of them are in green :-)

2022-06-20 07:12 UTC, agomezmoron commented
Hi @pozil ,

Did you have the chance to have a look on it? If I can help you with anything else just let me know :).

Cheers!

2022-06-20 07:25 UTC, pozil commented
@agomezmoron I didn't get the time to dive into it last week but I'll do it today. Stay tuned for feedback.

2022-06-20 07:41 UTC, pozil requested changes
Done reviewing. Thanks for the contrib once more. I've requested some minor changes.

2022-06-20 07:41 UTC, pozil commented on src/action.js
> +        // Assign issue
```suggestion
        // Assign PR
```

2022-06-20 07:41 UTC, pozil commented on .gitignore
> +node_modules
We need `node_modules` in git for the action to run.

2022-06-20 07:41 UTC, pozil commented on src/action.js
> +    let isIssue = context.issue ? true : false;
```suggestion
    let isIssue = context.hasOwnProperty('issue');
```

2022-06-20 07:41 UTC, pozil commented on src/action.js
> +const { getOctokit } = require('@actions/github');
Not used, please remove.
BTW this causes a linting error that fails the CI workflow so should try to run `npm run lint` locally to detect this in the future.

2022-06-20 07:49 UTC, agomezmoron commented on .gitignore
> +node_modules
Ok, I didn't know it

2022-06-20 07:51 UTC, agomezmoron commented on src/action.js
> +    let isIssue = context.issue ? true : false;
linter doesn't allow it ( 127:27  error  Do not access Object.prototype method 'hasOwnProperty' from target object  no-prototype-builtins)

2022-06-20 07:52 UTC, agomezmoron commented
I applied all the changes except one that is not allowed by the linter

2022-06-20 07:58 UTC, pozil approved these changes
Looking good thanks.

2022-06-20 07:58 UTC, merged